---
title: "Week03 Recitation"
author: "Sophie Kim"
date: "February 17, 2016"
output: html_document
---

```{r}
install.packages("kinship2")

tmpPedigreeDataFrame <- data.frame(
   id      =c("jodie", "john","belimo","belinda"),
   dadid   =c(NA,      NA,    "john",  "john"),
   momid   =c(NA,      NA,    "jodie", "jodie"),
   sex     =c("female","male","male",  "female"),
   affected=c(F,       F,     T,       F)
)

tmpPedigreeDataFrame

tmpPedigreeDataFrame$id
```

```{r}
with(tmpPedigreeDataFrame, id)
#[1] jodie   john    belimo  belinda
#Levels: belimo belinda jodie john
```
--> with allows you to access the second object forth with the first object



*relative risk: from one group to another (having the group of AA relative to "everything else")



1. (n!/(k!(n-k)!))

2. (p^k(1-p)^(n-k))

(n!/(k!(n-k)!)) * (p^k(1-p)^(n-k))


*using vectors in a math formula

```{r}
z <- 1:3
0.5^z

p <- 0.5
k <- 0:4
n <- 4
p^k * (1-p)^(n-k) #--> calculates each of the five different possibilities for 0:4


(factorial(n) / (factorial(k)*factorial(n-k))) * (p^k*(1-p)^(n-k))
```